name: My first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Welcome message
        run: echo "Siemanko"

      - name: List files
        run: ls -al

      - name: Interact with file in a repo
        run: cat README.md
    
