name: My first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Welcome message
        run: | 
          chmod +x hello.sh
          ./hello.sh
