name: solar system application testing
on:
  push:
    branches:
    - main
    - 'feature/*'
  workflow_dispatch:
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME : ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  unit-testing:
    name: CI testing for the nodejs application
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [18, 19, 20]
        exclude:
        - os: macos-latest
          version: 18
    steps:
    - name: checkout the code
      uses: actions/checkout@v4
    - name: install node js version ${{matrix.version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.version}}
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
          # npm cache files are stored in node_modules
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: install dependencies
      run: npm install
    - name: test the nodejs code with node test
      run: npm test
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: nodejs-artifact
        path: test-results.xml

  code-coverage:
    needs: unit-testing
    name: code coverage
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: install nodejs
      uses: actions/setup-node@v3
      with: 
        node-version: 18
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
            # npm cache files are stored in node_modules
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: install dependencies
      run: npm install
    - name: run code coverage
      run: npm run coverage
      continue-on-error: true
      
    - name: upload code coverage
      uses: actions/upload-artifact@v3
      with: 
        name: coverage-results
        path: coverage
        retention-days: 15



  